# Generated by Django 3.2.7 on 2021-09-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Limit_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('age', models.CharField(blank=True, max_length=400, null=True)),
                ('parent', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Column_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('parent', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(blank=True, max_length=400, null=True)),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fees_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('parent', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imp_Dates_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('date', models.CharField(blank=True, max_length=400, null=True)),
                ('parent', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Links_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(blank=True, max_length=400)),
                ('link', models.CharField(blank=True, max_length=400, null=True)),
                ('download_file', models.FileField(blank=True, null=True, upload_to='static/main/posts/uploads/%Y/%M/%D/')),
            ],
        ),
        migrations.CreateModel(
            name='Qual_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('parent', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Related_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('link', models.CharField(blank=True, max_length=400, null=True)),
                ('parent', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, max_length=400, null=True)),
                ('sub_parent', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('rowspan', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_heading', models.CharField(blank=True, max_length=400, null=True)),
                ('name_of_the_post', models.CharField(blank=True, max_length=400, null=True)),
                ('post_date', models.CharField(blank=True, max_length=400, null=True)),
                ('latest_update', models.CharField(blank=True, max_length=400, null=True)),
                ('vacancy', models.CharField(blank=True, max_length=400, null=True)),
                ('brief_info', models.TextField(blank=True, max_length=500, null=True)),
                ('table_header', models.CharField(blank=True, max_length=400, null=True)),
                ('table_header_name', models.CharField(blank=True, max_length=400, null=True)),
                ('advt_no', models.CharField(blank=True, max_length=400, null=True)),
                ('vacancy_header', models.CharField(blank=True, max_length=400, null=True)),
                ('vacancy_rows', models.IntegerField(blank=True, null=True)),
                ('age_limit_list', models.ManyToManyField(to='Posts.Age_Limit_List')),
                ('application_fee', models.ManyToManyField(to='Posts.Fees_List')),
                ('important_dates', models.ManyToManyField(to='Posts.Imp_Dates_List')),
                ('important_links', models.ManyToManyField(to='Posts.Links_List')),
                ('qualification_list', models.ManyToManyField(to='Posts.Qual_List')),
                ('related', models.ManyToManyField(to='Posts.Related_Posts')),
                ('vacancy_columns', models.ManyToManyField(to='Posts.Column_List')),
                ('vacancy_details_list', models.ManyToManyField(to='Posts.Vacancy_List')),
            ],
        ),
    ]
