# Generated by Django 3.2.7 on 2021-09-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links_list',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='staticfiles/posts/uploads/%Y/%M/%D/'),
        ),
    ]
