# Generated by Django 3.2.7 on 2021-10-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_links_list_download_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy_list',
            name='row_number',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
